### ISSUE TITLE
`calculate_ecat` does not work on grouped_df

### ISSUE THREAD

**Issue by wolfeclw** [erikarasnick/ecat#4]
If the tibble with lat/lon coordinates is grouped, the following error occurs:

*Error: Column `elevation` must be length 1 (the group size), not 343*
*In addition: Warning message:*
*In get_elevation(.) :*
  *The `raster` package has been attached to the global environment, masking dplyr::select()*

Could you create a warning message that the input tibble is grouped?

**Comment by cole-brokamp** [comment]
I think this is because the `mutate` call in the function is trying to apply it across each group in a grouped tibble: https://github.com/erikarasnick/ecat/blob/afb76dce550ea4b1df390399a32f1d89db7efcaa/R/ecat_and_scaling_functions.R#L53

This doesn't seem like intentional behavior from a user because nobody should have the need to use this function on a grouped tibble, so we should check to see if the input data.frame is grouped and either:

1. refuse to take grouped tibbles and return a more informative error message, or
2. ungroup the grouped tibble and report a warning message

If taking the latter approach should we return the tibble back to being grouped as it was?

Thoughts on best approach for this workflow?
