### ISSUE TITLE
error occurs when column named 'ecat' in input data frame

### ISSUE THREAD

**Issue by wolfeclw** [erikarasnick/ecat#5]
This error might be pretty rare, but if there is a column 'ecat' in the input data frame/tibble, the function fails and prints the warning message below:

*2: Unknown or uninitialised column: 'ecat'. *

This occurred because I was comparing old ecat values to values generated by `calculate_ecat.`  Could this also occur if someone calculates unscaled ecat and the wants to calculate scaled ecat in another column within that data frame?

**Comment by cole-brokamp** [comment]
i'm guessing this is coming because if there is a column named `ecat` in the original input data.frame then when it is `left_joined` back to the new data.frame with `ecat`, they will be renamed to `ecat.x` and `ecat.y`, respectively.

then, the error would occur here because there is not column named `ecat`, just columns named `ecat.x` and `ecat.y` https://github.com/erikarasnick/ecat/blob/afb76dce550ea4b1df390399a32f1d89db7efcaa/R/ecat_and_scaling_functions.R#L76-L78
